{% set name = "jekyll-compose" %}
{% set version = "0.12.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 0478638a921c5795b1e5b1ffdc769f3c405682e239b1de0117bde60af4edc8db

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-jekyll >=3.7,<5

test:
  commands:
    - ruby -r jekyll -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Streamline your writing in Jekyll with these commands.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/jekyll/{{ name }}

extra:
  recipe-maintainers:
    - sodre
    - bgruening
