travis:
  secure:
    BINSTAR_TOKEN: UU208R/CcRRkFPX5/G58JjP48RosiJHV806IfPSIbGy7Lf8OYQWg7umcBog321cj2lRxw7qTgw4h14t7SA1PaJ8U5qKtQ26mlnv/jHnrEZ5fLOehTcPMeuQqlyTJuFQHw7ZLOw9f9b1l7IATSKN2+oy6JO95JjhkzvLTaN2vmgpz8cIyI5k+cYH2hWP/9KAyeTeoubteN9GA14R3mdXwlhK68cN55E4L+lHbl0X6cmSoqKpCMTylXHJFkmycSmAfDA398gqspQRBdutYael+d0ChaWGm7Bz0Bw+T82K3vNSGhfcncvNriSpzXYJgQQq0sEfHm6Ooaqh/58ATwHlYWb3xGDR0hvmop4m8wek55JvWm3nq/kJuCX4wdXtBiICgiRlCMI/zsmwaTL9k3ZMw0k3BECFZHO4fznKyIZBfR6qubfdJwfU54NNO1jVRkUL1w9XC8Zr0jQ2DSLtbeastpNL7+RwgwV1EjKmFYFuDMrtTfEEVbm85Emh/5ar8VmxSWmDBPP7iKtOLIYCI8zyrle5BSjM6U2UqTt0Jo6I8H9hBSAzFLwNW/suF5K/YHPA9KxqbGoKWz/XKIfFRF8qDK02kmt+NGkzhMxWt51P8wHPHlXN9m49KnM7YGiAEekoCewfL8X0wUqji12yqxrHddOn7Nijz2tg1GQc38wtPosM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
